### ISSUE TITLE
Check-in generated artifacts of example app?

### ISSUE THREAD

**Issue by alloy** [kastermester/relay-compiler-language-typescript#17]
It might be nice for people to be able to quickly see real world artefacts and also for us to update those along with plugin changes so that we can review this _besides_ any other tests. What do you think?

**Comment by kastermester** [comment]
Seems good to me. Personally I'd never run an app like that, but I think it has been hinted that facebook does that - so lets go with that.

Also the reasons you noted are very valid.

**Comment by alloy** [comment]
Yeah I just found that they do so yesterday https://github.com/facebook/relay/commit/640e831b
